/// DES / 2K3DES / 3K3DES primitives for the *legacy* DESFire authentication
/// modes (`Authenticate` 0x0A and `AuthenticateISO` 0x1A).
///
/// These exist for exactly one reason: a **blank, never-personalised** DESFire
/// card has a PICC master key that is 16 zero bytes of type DES/2K3DES, and the
/// only way to talk to it is one of the pre-AES handshakes. Once the card has
/// been provisioned this file is never used again — everyday balance operations
/// run over `AuthenticateEV2First` (0x71) and AES-128 in
/// `desfire_crypto.dart`.
///
/// Every routine is a port of `desfire_crypto.c`
/// (`df_3des_cbc_encrypt`, `df_3des_cbc_decrypt`, `df_3des_ecb_decrypt`,
/// `df_3k3des_cbc_encrypt`, `df_3k3des_cbc_decrypt`, `df_des_cbc_encrypt`,
/// `df_des_cbc_decrypt`, `df_crc32`) and is pinned to vectors generated by
/// compiling that C file — see `test/desfire_legacy_crypto_test.dart`.
///
/// This library has no Flutter or NFC dependency, so it is fully unit testable.
library;

import 'dart:typed_data';

import 'package:pointycastle/export.dart';

/// DES block size in bytes. Note this is 8, not the 16 that AES uses; every
/// buffer in the legacy handshake is a multiple of 8.
const int kDesBlockSize = 8;

/// Expands a 16-byte 2K3DES key into the 24-byte `K1 | K2 | K1` form that a
/// three-key DES engine expects.
///
/// Port of the `memcpy(key24, key16, 16); memcpy(key24 + 16, key16, 8);`
/// prologue repeated in `df_3des_cbc_encrypt` / `df_3des_cbc_decrypt` /
/// `df_3des_ecb_decrypt`.
Uint8List expand2k3desKey(Uint8List key16) {
  _requireLength(key16, 16, '2K3DES key');
  final out = Uint8List(24);
  out.setRange(0, 16, key16);
  out.setRange(16, 24, key16);
  return out;
}

/// Expands an 8-byte single-DES key into the `K | K` form.
///
/// pointycastle 4.x ships no standalone single-DES engine, only [DESedeEngine].
/// Feeding it a 16-byte key sets `K1 == K2` (and it derives `K3 = K1`), so
/// `E_K1(D_K1(E_K1(x))) == E_K1(x)`: three-key DES with a doubled key *is*
/// single DES, exactly. `test/desfire_legacy_crypto_test.dart` pins this
/// against `df_des_cbc_encrypt` from the C.
Uint8List expandDesKey(Uint8List key8) {
  _requireLength(key8, 8, 'DES key');
  final out = Uint8List(16);
  out.setRange(0, 8, key8);
  out.setRange(8, 16, key8);
  return out;
}

/// 2K3DES CBC encryption. Port of `df_3des_cbc_encrypt`.
Uint8List des3CbcEncrypt(Uint8List key16, Uint8List iv8, Uint8List data) =>
    _cbc(expand2k3desKey(key16), iv8, data, forEncryption: true);

/// 2K3DES CBC decryption. Port of `df_3des_cbc_decrypt`.
Uint8List des3CbcDecrypt(Uint8List key16, Uint8List iv8, Uint8List data) =>
    _cbc(expand2k3desKey(key16), iv8, data, forEncryption: false);

/// 2K3DES ECB encryption — the raw block primitive, no chaining.
///
/// Not in the C (which only exports the decrypt direction) but needed to model
/// the *card* side in tests and to build [desfireLegacyCbcSend].
Uint8List des3EcbEncrypt(Uint8List key16, Uint8List data) =>
    _ecb(expand2k3desKey(key16), data, forEncryption: true);

/// 2K3DES ECB decryption. Port of `df_3des_ecb_decrypt`.
Uint8List des3EcbDecrypt(Uint8List key16, Uint8List data) =>
    _ecb(expand2k3desKey(key16), data, forEncryption: false);

/// 3K3DES CBC encryption with a 24-byte key. Port of `df_3k3des_cbc_encrypt`.
Uint8List des3k3CbcEncrypt(Uint8List key24, Uint8List iv8, Uint8List data) {
  _requireLength(key24, 24, '3K3DES key');
  return _cbc(key24, iv8, data, forEncryption: true);
}

/// 3K3DES CBC decryption with a 24-byte key. Port of `df_3k3des_cbc_decrypt`.
Uint8List des3k3CbcDecrypt(Uint8List key24, Uint8List iv8, Uint8List data) {
  _requireLength(key24, 24, '3K3DES key');
  return _cbc(key24, iv8, data, forEncryption: false);
}

/// Single-DES CBC encryption. Port of `df_des_cbc_encrypt`.
Uint8List desCbcEncrypt(Uint8List key8, Uint8List iv8, Uint8List data) =>
    _cbc(expandDesKey(key8), iv8, data, forEncryption: true);

/// Single-DES CBC decryption. Port of `df_des_cbc_decrypt`.
Uint8List desCbcDecrypt(Uint8List key8, Uint8List iv8, Uint8List data) =>
    _cbc(expandDesKey(key8), iv8, data, forEncryption: false);

/// The DESFire *native* (D40) "CBC send" transform used by the PCD in a legacy
/// `Authenticate` (0x0A) handshake.
///
/// The structural oddity of D40 is that the reader applies the **decrypt**
/// primitive in both directions. Sending is therefore
/// `c[i] = DEC(p[i] XOR c[i-1])`, with `c[-1] = iv8` — the same chaining as
/// ordinary CBC encryption, but with the block cipher run backwards.
///
/// ## Why this differs from `df_authenticate_legacy`
///
/// The C builds its step-2 token with `df_3des_cbc_encrypt` (ordinary CBC, the
/// *encrypt* primitive), i.e. the ISO/EV1 construction rather than the D40 one.
/// That code nevertheless works against real blank cards, and the reason is
/// worth writing down: the factory PICC master key is 16 zero bytes, an
/// all-zero DES key is one of the classic DES **weak keys**, and for a weak key
/// every round subkey is identical, which makes `E_K == D_K`. The two
/// constructions are therefore byte-for-byte identical for the only key this
/// app ever presents at PICC level. `test/desfire_legacy_crypto_test.dart`
/// pins both against the C and demonstrates that they agree for the zero key
/// and diverge for a non-zero one.
///
/// This function implements the D40 direction because it is correct for both
/// cases; [DesfireCard.authenticateLegacy] falls back to the C's construction
/// if a card rejects it.
Uint8List desfireLegacyCbcSend(Uint8List key16, Uint8List iv8, Uint8List data) {
  _requireLength(iv8, kDesBlockSize, 'IV');
  _requireBlockAligned(data);
  final out = Uint8List(data.length);
  var chain = Uint8List.fromList(iv8);
  for (var off = 0; off < data.length; off += kDesBlockSize) {
    final block = Uint8List(kDesBlockSize);
    for (var i = 0; i < kDesBlockSize; i++) {
      block[i] = data[off + i] ^ chain[i];
    }
    final enciphered = des3EcbDecrypt(key16, block);
    out.setRange(off, off + kDesBlockSize, enciphered);
    chain = enciphered;
  }
  return out;
}

/// The D40 "CBC receive" transform: `p[i] = DEC(c[i]) XOR c[i-1]`.
///
/// This is plain CBC decryption, so it is identical to [des3CbcDecrypt] — the
/// alias exists so the two halves of the handshake read symmetrically at the
/// call site.
Uint8List desfireLegacyCbcReceive(
  Uint8List key16,
  Uint8List iv8,
  Uint8List data,
) => des3CbcDecrypt(key16, iv8, data);

/// CRC-32 as DESFire computes it. Port of `df_crc32`.
///
/// Reflected CRC-32 (polynomial 0xEDB88320, init 0xFFFFFFFF) **without** the
/// final complement that the common "CRC-32/ISO-HDLC" definition applies. So
/// `crc32("123456789")` is `0x340BC6D9`, the ones' complement of the familiar
/// `0xCBF43926`. Getting this wrong would make `ChangeKey` fail with an
/// integrity error, so it is pinned against the C in the tests.
int desfireCrc32(Uint8List data) {
  var crc = 0xFFFFFFFF;
  for (final byte in data) {
    crc ^= byte;
    for (var j = 0; j < 8; j++) {
      crc = (crc & 1) != 0 ? (crc >> 1) ^ 0xEDB88320 : crc >> 1;
    }
  }
  return crc & 0xFFFFFFFF;
}

/// Encodes [crc] as 4 little-endian bytes, the order `df_change_key` writes it.
Uint8List crc32ToBytes(int crc) => Uint8List.fromList([
  crc & 0xFF,
  (crc >> 8) & 0xFF,
  (crc >> 16) & 0xFF,
  (crc >> 24) & 0xFF,
]);

Uint8List _ecb(Uint8List key, Uint8List data, {required bool forEncryption}) {
  _requireBlockAligned(data);
  final engine = DESedeEngine()..init(forEncryption, KeyParameter(key));
  final out = Uint8List(data.length);
  for (var off = 0; off < data.length; off += kDesBlockSize) {
    engine.processBlock(data, off, out, off);
  }
  return out;
}

Uint8List _cbc(
  Uint8List key,
  Uint8List iv,
  Uint8List data, {
  required bool forEncryption,
}) {
  _requireLength(iv, kDesBlockSize, 'IV');
  _requireBlockAligned(data);
  final cipher = CBCBlockCipher(DESedeEngine())
    ..init(forEncryption, ParametersWithIV(KeyParameter(key), iv));
  final out = Uint8List(data.length);
  for (var off = 0; off < data.length; off += kDesBlockSize) {
    cipher.processBlock(data, off, out, off);
  }
  return out;
}

void _requireBlockAligned(Uint8List data) {
  if (data.length % kDesBlockSize != 0) {
    throw ArgumentError.value(
      data.length,
      'data',
      'DES payload must be a multiple of $kDesBlockSize bytes',
    );
  }
}

void _requireLength(Uint8List value, int length, String name) {
  if (value.length != length) {
    throw ArgumentError.value(
      value.length,
      name,
      '$name must be exactly $length bytes',
    );
  }
}
