import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_topup/desfire/desfire_crypto.dart';

/// Known-answer tests for the crypto layer.
///
/// Two independent sources of truth are used:
///
/// 1. **RFC 4493 / NIST SP 800-38B** for AES-CMAC, and FIPS 197 for the raw
///    AES block operation. These prove the primitives are standard.
/// 2. **Vectors generated by compiling and running the project's own C
///    implementation** (`plainc-desfire-rc522-main/lib/desfire/desfire_crypto.c`)
///    for session-key derivation, IV construction, MAC truncation and CBC.
///    These prove the Dart port is bit-identical to the code the cards were
///    personalised with — which matters more than matching the datasheet,
///    because a divergence there would silently break every card in the field.
void main() {
  group('AES-CMAC (RFC 4493 known-answer vectors)', () {
    // RFC 4493 section 4, "Test Vectors", key K.
    final key = fromHex('2b7e151628aed2a6abf7158809cf4f3c');

    // The RFC's message M, from which each example takes a prefix.
    final message = fromHex(
      '6bc1bee22e409f96e93d7e117393172a'
      'ae2d8a571e03ac9c9eb76fac45af8e51'
      '30c81c46a35ce411e5fbc1191a0a52ef'
      'f69f2445df4f9b17ad2b417be66c3710',
    );

    test('Example 1: len = 0', () {
      expect(
        toHex(aesCmac(key, Uint8List(0))),
        equalsIgnoringCase(toHex(fromHex('bb1d6929e95937287fa37d129b756746'))),
      );
    });

    test('Example 2: len = 16', () {
      expect(
        aesCmac(key, Uint8List.sublistView(message, 0, 16)),
        fromHex('070a16b46b4d4144f79bdd9dd04a287c'),
      );
    });

    test('Example 3: len = 40', () {
      expect(
        aesCmac(key, Uint8List.sublistView(message, 0, 40)),
        fromHex('dfa66747de9ae63030ca32611497c827'),
      );
    });

    test('Example 4: len = 64', () {
      expect(
        aesCmac(key, message),
        fromHex('51f0bebf7e3b9d92fc49741779363cfe'),
      );
    });

    test('rejects keys that are not 16 bytes', () {
      expect(
        () => aesCmac(Uint8List(8), Uint8List(0)),
        throwsA(isA<ArgumentError>()),
      );
    });
  });

  group('AES-128 ECB (FIPS 197 known-answer vector)', () {
    // FIPS 197 Appendix B / C.1.
    final key = fromHex('000102030405060708090a0b0c0d0e0f');
    final plaintext = fromHex('00112233445566778899aabbccddeeff');
    final ciphertext = fromHex('69c4e0d86a7b0430d8cdb78070b4c55a');

    test('encrypts the reference block', () {
      expect(aesEcbEncryptBlock(key, plaintext), ciphertext);
    });

    test('decrypts the reference block', () {
      expect(aesEcbDecryptBlock(key, ciphertext), plaintext);
    });
  });

  group('AES-128 CBC (vector generated from desfire_crypto.c)', () {
    final key = Uint8List.fromList(List<int>.filled(16, 0x22));
    final iv = Uint8List.fromList(List<int>.generate(16, (i) => i));
    final plaintext = Uint8List.fromList(
      List<int>.generate(32, (i) => 0x30 + i),
    );
    // df_aes_cbc_encrypt(key, iv, pt, 32, ct)
    final expected = fromHex(
      '5880b8078b279f2b286cb883039296ff'
      '7761837fd09336ff8b87b08749050ae7',
    );

    test('matches the C implementation over two blocks', () {
      expect(aesCbcEncrypt(key, iv, plaintext), expected);
    });

    test('decrypt is the inverse of encrypt', () {
      expect(aesCbcDecrypt(key, iv, expected), plaintext);
    });

    test('rejects payloads that are not block aligned', () {
      expect(
        () => aesCbcEncrypt(key, iv, Uint8List(17)),
        throwsA(isA<ArgumentError>()),
      );
    });
  });

  group('MAC truncation', () {
    test('keeps the odd-indexed bytes, matching df_truncate_mac', () {
      // df_truncate_mac over F0 F1 ... FF
      final mac = Uint8List.fromList(List<int>.generate(16, (i) => 0xF0 + i));
      expect(truncateMac(mac), fromHex('f1f3f5f7f9fbfdff'));
    });

    test('produces 8 bytes from any 16-byte CMAC', () {
      final mac = fromHex('9172a6f9b079bae1268f69e5075d5679');
      expect(truncateMac(mac), fromHex('72f979e18fe55d79'));
      expect(truncateMac(mac), hasLength(8));
    });

    test('rejects a MAC that is not 16 bytes', () {
      expect(() => truncateMac(Uint8List(8)), throwsA(isA<ArgumentError>()));
    });
  });

  group('session key derivation (vectors from df_derive_session_key)', () {
    final key = Uint8List.fromList(List<int>.filled(16, 0x22));
    final rndA = Uint8List.fromList(List<int>.generate(16, (i) => 0x10 + i));
    final rndB = Uint8List.fromList(List<int>.generate(16, (i) => 0xA0 + i));

    test('SV1 (0xA5) yields the encryption session key', () {
      expect(
        deriveSessionKey(key, rndA, rndB, SessionKeyLabel.enc),
        fromHex('1130b90c1aac6ef7528d9088d24d67d3'),
      );
    });

    test('SV2 (0x5A) yields the MAC session key', () {
      expect(
        deriveSessionKey(key, rndA, rndB, SessionKeyLabel.mac),
        fromHex('569031dca11d038e1b12e50092c9e030'),
      );
    });

    test('a different base key yields different session keys', () {
      final key2 = Uint8List.fromList(List<int>.generate(16, (i) => i * 7 + 1));
      expect(
        deriveSessionKey(key2, rndA, rndB, SessionKeyLabel.enc),
        fromHex('b23c6a4824b06d0a9a80f4d97b04c1a0'),
      );
      expect(
        deriveSessionKey(key2, rndA, rndB, SessionKeyLabel.mac),
        fromHex('38f8a067735f1c14f2d59862ddc08928'),
      );
    });

    test('enc and MAC keys differ for the same nonces', () {
      final enc = deriveSessionKey(key, rndA, rndB, SessionKeyLabel.enc);
      final mac = deriveSessionKey(key, rndA, rndB, SessionKeyLabel.mac);
      expect(enc, isNot(mac));
    });

    test('changing one bit of RndA changes both session keys', () {
      final tweaked = Uint8List.fromList(rndA)..[0] ^= 0x01;
      expect(
        deriveSessionKey(key, tweaked, rndB, SessionKeyLabel.enc),
        isNot(deriveSessionKey(key, rndA, rndB, SessionKeyLabel.enc)),
      );
    });

    test('rejects an unknown label', () {
      expect(
        () => deriveSessionKey(key, rndA, rndB, 0x99),
        throwsA(isA<ArgumentError>()),
      );
    });
  });

  group('EV2 IV construction (vectors from _calc_iv_cmd / _calc_iv_resp)', () {
    // sessKeyEnc as derived above.
    final sessKeyEnc = fromHex('1130b90c1aac6ef7528d9088d24d67d3');
    final ti = fromHex('deadbeef');

    test('command IV at counter 0', () {
      expect(
        calcIvCommand(sessKeyEnc, ti, 0),
        fromHex('d2cbbe3ac67413450a0002aac5eb6f7e'),
      );
    });

    test('command IV at counter 1', () {
      expect(
        calcIvCommand(sessKeyEnc, ti, 1),
        fromHex('62401812ce134067317a51e9e53cab26'),
      );
    });

    test('command IV at counter 2', () {
      expect(
        calcIvCommand(sessKeyEnc, ti, 2),
        fromHex('43a1e3e696b327031557b7e308c03028'),
      );
    });

    test('command IV at counter 258 spans both counter bytes', () {
      expect(
        calcIvCommand(sessKeyEnc, ti, 0x0102),
        fromHex('87607cb04919b91b20d19bb7abf104a7'),
      );
    });

    test('response IV at counter 0 uses the 5A A5 prefix', () {
      expect(
        calcIvResponse(sessKeyEnc, ti, 0),
        fromHex('523a4c5afaa44a24c7cf9a8467b8fc59'),
      );
    });

    test('response IV at counter 1', () {
      expect(
        calcIvResponse(sessKeyEnc, ti, 1),
        fromHex('1853b1b241df7dc4191451b7f9febfff'),
      );
    });

    test('command and response IVs differ at the same counter', () {
      expect(
        calcIvCommand(sessKeyEnc, ti, 5),
        isNot(calcIvResponse(sessKeyEnc, ti, 5)),
      );
    });

    test('rejects a TI that is not 4 bytes', () {
      expect(
        () => calcIvCommand(sessKeyEnc, Uint8List(3), 0),
        throwsA(isA<ArgumentError>()),
      );
    });
  });

  group('ISO 7816-4 padding', () {
    test('appends 0x80 and pads to the next 16-byte boundary', () {
      // 4-byte value 500 (little-endian) -> one padded block.
      expect(
        padIso7816(fromHex('f4010000')),
        fromHex('f4010000800000000000000000000000'),
      );
    });

    test('a full block still gains a whole block of padding', () {
      final input = Uint8List.fromList(List<int>.filled(16, 0xAB));
      final padded = padIso7816(input);
      expect(padded.length, 32);
      expect(padded[16], 0x80);
      expect(padded.sublist(17), everyElement(0));
    });

    test('empty input pads to one block', () {
      final padded = padIso7816(Uint8List(0));
      expect(padded.length, 16);
      expect(padded[0], 0x80);
    });

    test('unpad reverses pad', () {
      for (final length in [0, 1, 4, 15, 16, 17, 31]) {
        final input = Uint8List.fromList(
          List<int>.generate(length, (i) => (i * 13 + 7) & 0xFF),
        );
        expect(unpadIso7816(padIso7816(input)), input, reason: 'len $length');
      }
    });
  });

  group('helpers', () {
    test('rotateLeft1 moves the first byte to the end', () {
      expect(rotateLeft1(fromHex('00112233')), fromHex('11223300'));
    });

    test('rotateLeft1 over 16 bytes matches the auth handshake', () {
      final rndB = Uint8List.fromList(List<int>.generate(16, (i) => 0xA0 + i));
      final rotated = rotateLeft1(rndB);
      expect(rotated.first, 0xA1);
      expect(rotated.last, 0xA0);
      expect(rotated, hasLength(16));
    });

    test('bytesEqual compares content, not identity', () {
      expect(bytesEqual(fromHex('0102'), fromHex('0102')), isTrue);
      expect(bytesEqual(fromHex('0102'), fromHex('0103')), isFalse);
      expect(bytesEqual(fromHex('0102'), fromHex('010203')), isFalse);
    });

    test('fromHex ignores separators and round-trips through toHex', () {
      expect(fromHex('DE AD:BE-EF'), fromHex('deadbeef'));
      expect(toHex(fromHex('deadbeef')), 'DE AD BE EF');
    });

    test('fromHex rejects an odd digit count', () {
      expect(() => fromHex('abc'), throwsA(isA<ArgumentError>()));
    });
  });
}
